
export const PRODUCT_CATEGORIES = [
  { nameAr: "أدوات أكل (سكاكين، شوك، ملاعق)", number: "1101" },
  { nameAr: "شراشف وأغطية طاولات", number: "1102" },
  { nameAr: "أطباق للاستخدام الواحد (بلاستيك)", number: "1103" },
  { nameAr: "أطباق للاستخدام الواحد (فلين)", number: "1104" },
  { nameAr: "أوعية وقوالب للطهي والتقديم (قصدير)", number: "1105" },
  { nameAr: "أطباق وعلب للاستخدام الواحد (ورق وكرتون)", number: "1106" },
  { nameAr: "أدوات ومستلزمات طهي وتقديم", number: "1107" },
  { nameAr: "علب وأكواب حلويات (كريستال/بلاستيك)", number: "1108" },
  { nameAr: "كاسات وفناجين (بلاستيك وكرتون)", number: "1110" },
  { nameAr: "مستلزمات كاسات (أغطية، مصاص، حراكات)", number: "1111" },
  { nameAr: "دلاء وأوعية تنظيف", number: "1201" },
  { nameAr: "فوط ومماسح تنظيف", number: "1202" },
  { nameAr: "قشاطات (أرضيات وزجاج)", number: "1203" },
  { nameAr: "ليف وسلك جلي", number: "1204" },
  { nameAr: "مجاريد", number: "1205" },
  { nameAr: "مكانس وفراشي تنظيف", number: "1206" },
  { nameAr: "عصي ومقابض أدوات تنظيف", number: "1207" },
  { nameAr: "موزعات صابون سائل ورغوة", number: "1301" },
  { nameAr: "أجهزة طارد الحشرات", number: "1302" },
  { nameAr: "موزعات محارم تنشيف", number: "1303" },
  { nameAr: "موزعات ورق تواليت", number: "1304" },
  { nameAr: "موزعات مناديل طاولة (نابكنز)", number: "1305" },
  { nameAr: "موزعات معطر جو", number: "1306" },
  { nameAr: "أجهزة تنشيف كهربائية", number: "1307" },
  { nameAr: "مماسح احترافية", number: "1401" },
  { nameAr: "قشاطات احترافية (أرضيات وزجاج)", number: "1402" },
  { nameAr: "مجاريد احترافية", number: "1403" },
  { nameAr: "فراشي ومنافض غبار احترافية", number: "1404" },
  { nameAr: "عصي تلسكوبية وملحقات", number: "1405" },
  { nameAr: "مكاشط (شبختل) وشفرات", number: "1406" },
  { nameAr: "عربات تنظيف وخدمة", number: "1407" },
  { nameAr: "سلال وحاويات قمامة", number: "1501" },
  { nameAr: "شنط وأكياس (بلاستيك وورق)", number: "1601" },
  { nameAr: "رولات تغليف (نايلون وقصدير)", number: "1602" },
  { nameAr: "ورق زبدة", number: "1603" },
  { nameAr: "علب بلاستيك بغطاء ثابت/مدمج", number: "1604" },
  { nameAr: "علب بلاستيك بغطاء منفصل", number: "1605" },
  { nameAr: "علب كرتون وورق حلويات", number: "1606" },
  { nameAr: "علب صلصات وتوابل (بلاستيك)", number: "1607" },
  { nameAr: "لواصق وأشرطة تغليف", number: "1608" },
  { nameAr: "مواد تغليف صناعية", number: "1609" },
  { nameAr: "أغطية علب طعام", number: "1610" },
  { nameAr: "ورق لف (صيدلية)", number: "1611" },
  { nameAr: "شفرات ومستلزمات حلاقة", number: "1701" },
  { nameAr: "فوط صحية", number: "1702" },
  { nameAr: "كريمات ومرطبات بشرة", number: "1703" },
  { nameAr: "ليف استحمام", number: "1704" },
  { nameAr: "مزيلات عرق", number: "1705" },
  { nameAr: "معاجين وفراشي أسنان", number: "1706" },
  { nameAr: "قطن وأعواد تنظيف أذن وأسنان", number: "1707" },
  { nameAr: "شامبو وغسول جسم", number: "1708" },
  { nameAr: "صابون قطع", number: "1709" },
  { nameAr: "شاي وأعشاب ومشروبات ساخنة", number: "1801" },
  { nameAr: "بسكويت وحلويات جافة للضيافة", number: "1802" },
  { nameAr: "قهوة ومبيضات قهوة", number: "1803" },
  { nameAr: "مياه معدنية وعصائر", number: "1804" },
  { nameAr: "مواد تموينية أساسية", number: "1805" },
  { nameAr: "محارم تنشيف", number: "1901" },
  { nameAr: "ورق تواليت", number: "1902" },
  { nameAr: "مفروشات طبية ورقية (شراشف)", number: "1903" },
  { nameAr: "محارم مبللة", number: "1904" },
  { nameAr: "مناديل طاولة (نابكنز)", number: "1905" },
  { nameAr: "محارم وجه (علب وجيب)", number: "1906" },
  { nameAr: "أغطية مقاعد حمامات ورقية", number: "1907" },
  { nameAr: "علب محارم فارغة (للتعبئة)", number: "1908" },
  { nameAr: "ملابس وقائية (جاون، مريول، طواقي)", number: "2001" },
  { nameAr: "منظفات وملمعات أسطح وزجاج", number: "2101" },
  { nameAr: "صابون سائل ورغوة للأيدي", number: "2102" },
  { nameAr: "مزيلات بقع (ملابس وسجاد)", number: "2103" },
  { nameAr: "منظفات ومستلزمات غسالات صحون", number: "2104" },
  { nameAr: "مزيلات دهون وشحوم", number: "2105" },
  { nameAr: "معقمات طبية ومطهرات", number: "2107" },
  { nameAr: "غسيل ملابس", number: "2108" },
  { nameAr: "مبيضات (كلور)", number: "2109" },
  { nameAr: "مبيدات حشرية وقوارض", number: "2110" },
  { nameAr: "منظفات ومعطرات أرضيات وحمامات", number: "2111" },
  { nameAr: "معطرات جو", number: "2112" },
  { nameAr: "معقمات ومطهرات عامة", number: "2113" },
  { nameAr: "مبيدات قوارض (فونيك)", number: "2114" },
  { nameAr: "أكياس نفايات", number: "2201" },
  { nameAr: "أكياس طعام وتفريز", number: "2202" },
  { nameAr: "أكياس تسوق (شنط)", number: "2203" },
  { nameAr: "بطاريات", number: "2301" },
  { nameAr: "ولاعات وتعبئة غاز", number: "2302" },
  { nameAr: "فحم ومستلزمات إشعال", number: "2303" },
  { nameAr: "مستلزمات ديكور وزينة (ورد مجفف)", number: "2304" },
  { nameAr: "أوعية منزلية متنوعة", number: "2305" },
  { nameAr: "مستلزمات منزلية", number: "2306" },
] as const;

export function getCategoryByNumber(number: string) {
  return PRODUCT_CATEGORIES.find(cat => cat.number === number);
}

export function getAllCategories() {
  return PRODUCT_CATEGORIES;
}
